
from collections.abc import Sequence
from typing import Any, Optional

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeAlias

_U8: TypeAlias = npt.NDArray[np.uint8]

class UnionFindDecoder:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def batch_decode(self, syndromes: _U8) -> _U8: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class FastUnionFindDecoder:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def batch_decode(self, syndromes: _U8) -> _U8: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class BlossomDecoder:
    def __init__(
        self,
        check_to_qubits: Sequence[Sequence[int]],
        n_qubits: Optional[int] = None,
        edge_weights: Optional[Sequence[float]] = None,
    ) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def batch_decode(self, syndromes: _U8) -> _U8: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...
    @property
    def edges(self) -> list: ...

class SlidingWindowDecoder:
    def __init__(
        self,
        check_to_qubits: Sequence[Sequence[int]],
        n_qubits: Optional[int] = None,
        window_size: int = 10,
        decay_factor: float = 0.8,
    ) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def update(self, round_syndrome: _U8) -> _U8: ...
    def flush(self) -> None: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...
    @property
    def window_size(self) -> int: ...
    @property
    def decay_factor(self) -> float: ...
    @property
    def current_round(self) -> int: ...

class StreamingDecoder:
    def __init__(
        self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None, history_size: int = 10
    ) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def update(self, round_syndrome: _U8) -> _U8: ...
    def flush(self) -> None: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class BatchDecoder:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None) -> None: ...
    def parallel_batch_decode(self, syndromes: _U8) -> _U8: ...
    def batch_decode(self, syndromes: _U8) -> _U8: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class CPUBatchDecoder:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def batch_decode(self, syndromes: _U8) -> _U8: ...
    def batch_decode_par(self, syndromes: _U8) -> _U8: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class OpenCLBatchDecoder:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None) -> None: ...
    def batch_decode(self, syndromes: _U8) -> _U8: ...
    def reset(self) -> None: ...
    @staticmethod
    def is_available() -> bool: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...
    @property
    def device_name(self) -> str: ...
    @property
    def consecutive_failures(self) -> int: ...
    @property
    def total_failures(self) -> int: ...
    @property
    def is_degraded(self) -> bool: ...
    @property
    def gpu_recoveries(self) -> int: ...

class CUDABatchDecoder:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None) -> None: ...
    def batch_decode(self, syndromes: _U8) -> _U8: ...
    def reset(self) -> None: ...
    @staticmethod
    def is_available() -> bool: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...
    @property
    def device_name(self) -> str: ...
    @property
    def compute_capability(self) -> tuple[int, int]: ...
    @property
    def consecutive_failures(self) -> int: ...
    @property
    def total_failures(self) -> int: ...
    @property
    def is_degraded(self) -> bool: ...
    @property
    def gpu_recoveries(self) -> int: ...

class SparseBlossomDecoder:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def decode_with_weights(self, syndrome: _U8, weights: list[tuple[int, float]]) -> _U8: ...
    def batch_decode(self, syndromes: _U8) -> _U8: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class BPOSDDecoder:
    def __init__(
        self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None, error_rate: float = 0.1
    ) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def decode_timed(self, syndrome: _U8, max_latency_ms: float = 10.0) -> _U8: ...
    def bp_decode(self, syndrome: _U8, max_iterations: int = 20) -> npt.NDArray[np.float64]: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class NeuralPredecoder:
    def __init__(
        self, n_input: int, n_output: int, n_hidden1: Optional[int] = None, n_hidden2: Optional[int] = None
    ) -> None: ...
    def train(self, syndromes: _U8, corrections: _U8, n_epochs: int, learning_rate: float = 0.01) -> None: ...
    def predict(self, syndrome: _U8) -> _U8: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    @property
    def n_input(self) -> int: ...
    @property
    def n_output(self) -> int: ...
    @property
    def n_hidden1(self) -> int: ...
    @property
    def n_hidden2(self) -> int: ...

class GNNPredecoder:
    NODE_FEAT_DIM: int = 10
    EDGE_FEAT_DIM: int = 8
    def __init__(
        self,
        node_feat_dim: Optional[int] = None,
        edge_feat_dim: Optional[int] = None,
        hidden_size: int = 16,
        n_layers: int = 2,
    ) -> None: ...
    @classmethod
    def new_standard(cls, hidden_size: int = 16, n_layers: int = 2) -> GNNPredecoder: ...
    def forward(self, graph: DetectorGraph) -> list[float]: ...
    def train(self, graphs: list[DetectorGraph], targets: list[list[float]], n_epochs: int) -> None: ...
    def predict_with_node_probs(self, graph: DetectorGraph) -> tuple[list[float], list[float]]: ...
    def save_weights(self, path: str) -> None: ...
    def load_weights(self, path: str) -> None: ...
    @property
    def learning_rate(self) -> float: ...
    @learning_rate.setter
    def learning_rate(self, lr: float) -> None: ...
    @property
    def l2_lambda(self) -> float: ...
    @l2_lambda.setter
    def l2_lambda(self, val: float) -> None: ...

class DetectorGraph:
    NODE_FEAT_DIM: int = 10
    EDGE_FEAT_DIM: int = 8
    def __init__(
        self,
        check_to_qubits: Any,
        syndrome: Any,
        check_positions: Any = None,
        check_types: Any = None,
        base_weights: Any = None,
        n_qubits: Optional[int] = None,
    ) -> None: ...
    def update_syndrome(self, syndrome: Any) -> None: ...
    @property
    def n_nodes(self) -> int: ...
    @property
    def n_edges(self) -> int: ...
    @property
    def node_features(self) -> Any: ...
    @property
    def edge_features(self) -> Any: ...
    @property
    def edge_qubit_id(self) -> Any: ...
    @property
    def edge_src(self) -> Any: ...
    @property
    def edge_dst(self) -> Any: ...

class GNNTrainer:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: int, error_rate: float = 0.1) -> None: ...
    def train(self, gnn: GNNPredecoder, n_samples: int, n_epochs: int) -> float: ...
    def train_bp(self, gnn: GNNPredecoder, n_samples: int, n_epochs: int, max_bp_iter: int = 20) -> float: ...
    def generate_dataset(self, n_samples: int) -> int: ...

class LERBenchmark:
    def __init__(self) -> None: ...
    def run_all(self) -> str: ...

class HybridDecoder:
    def __init__(
        self,
        check_to_qubits: Any,
        n_qubits: Optional[int] = None,
        check_positions: Any = None,
        check_types: Any = None,
        base_weights: Any = None,
        gnn_hidden_size: int = 64,
        gnn_n_layers: int = 3,
    ) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def decode_hybrid(self, syndrome: _U8) -> _U8: ...
    def decode_heuristic(self, syndrome: _U8) -> _U8: ...
    def decode_standard(self, syndrome: _U8) -> _U8: ...
    def batch_decode_hybrid(self, syndromes: _U8) -> _U8: ...
    def batch_decode_standard(self, syndromes: _U8) -> _U8: ...
    def save_weights(self, path: str) -> None: ...
    def load_weights(self, path: str) -> None: ...
    def train(self, n_samples: int, n_epochs: int, error_rate: float = 0.1) -> float: ...
    def train_bp(self, n_samples: int, n_epochs: int, error_rate: float = 0.1, max_bp_iter: int = 20) -> float: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class DecoderPool:
    def __init__(
        self,
        check_to_qubits: Sequence[Sequence[int]],
        n_qubits: Optional[int] = None,
        decoder_type: str = "fast_union_find",
        n_workers: Optional[int] = None,
    ) -> None: ...
    def decode(self, syndromes: _U8) -> _U8: ...
    def close(self) -> None: ...
    @property
    def n_workers(self) -> int: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class AutoDecoder:
    def __init__(
        self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None, config: Optional[Any] = None
    ) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def batch_decode(self, syndromes: _U8) -> _U8: ...
    def calibrate(self, max_samples: int = 2048) -> None: ...
    def diagnostics(self) -> dict: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class BackendConfig:
    rayon_threshold: int
    gpu_threshold: int
    allow_gpu: bool
    prefer: str
    force: Optional[str]

class Backend:
    CPU_SINGLE: str
    CPU_RAYON: str
    CUDA: str
    OPENCL: str

class DecodeResult:
    correction: _U8
    syndrome: _U8
    faithful: bool
    decoder_name: str
    latency_us: float

class BeliefMatching:
    @classmethod
    def from_check_to_qubits(
        cls, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None, error_rate: float = 0.1
    ) -> BeliefMatching: ...
    @classmethod
    def from_numpy_h(cls, h_matrix: Any, error_rate: float = 0.1) -> BeliefMatching: ...

class BpOsdDecoder:
    def __init__(
        self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None, error_rate: float = 0.1
    ) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...

class PredecodedDecoder:
    def __init__(self, inner_decoder: Any) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...

class Workbench:
    def __init__(self) -> None: ...
    def run(self, tool_name: str, **kwargs: Any) -> Any: ...

class LookupTableDecoder:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: Optional[int] = None) -> None: ...
    def build_table(self, max_entries: int) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def batch_decode(self, syndromes: _U8) -> _U8: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...
    @property
    def table_size(self) -> int: ...

class BenchmarkSuite:
    def __init__(
        self,
        check_to_qubits: Sequence[Sequence[int]],
        n_qubits: Optional[int] = None,
        n_samples: int = 10000,
        seed: int = 42,
    ) -> None: ...
    def run(self) -> Any: ...
    def save(self, path: str, results: Any) -> None: ...

def check_to_edges(check_to_qubits: Any) -> Any: ...
def generate_surface_code_checks(distance: int) -> Any: ...
def generate_toy_code_checks(distance: int) -> Any: ...
def generate_ring_code_checks(distance: int) -> Any: ...
def generate_repetition_code_checks(distance: int) -> Any: ...
def run_mcp_server() -> None: ...
def cuda_is_available() -> bool: ...
def opencl_is_available() -> bool: ...
def run_grpc_server() -> None: ...
def start_metrics_server() -> None: ...
def get_decoder(check_to_qubits: Any, n_qubits: int, decoder_type: str = "blossom") -> Any: ...
def clear_decoder_cache() -> None: ...
def get_decoder_pool(
    check_to_qubits: Any, n_qubits: int, decoder_type: str = "union_find", n_workers: int = 4
) -> Any: ...
def decode_mmap(syndrome_path: str, correction_path: str, check_to_qubits: Any, n_qubits: int) -> dict: ...

__version__: str
